# Параметры DVC пайплайна для рекомендательной системы
# Отслеживаются DVC для автоматического обнаружения изменений

# Параметры обработки данных
data:
  split_mode: "user"  # "user" или "global"
  min_user_interactions: 5
  min_item_interactions: 5
  test_size: 0.15

# Веса событий для построения interactions
weights:
  view: 1.0
  addtocart: 4.0
  transaction: 8.0

# Параметры ALS модели
als:
  factors: 256
  iterations: 25
  regularization: 0.1
  alpha: 4.0
  random_state: 42
  num_threads: 0  # 0 = использовать все доступные потоки

# Параметры Content-Based Re-ranking
rerank:
  enabled: true
  alpha: 0.6  # Вес ALS score (1/rank)
  beta: 0.4   # Вес category score
  adaptive: true  # Адаптивное переранжирование

# Параметры генерации рекомендаций
recommendations:
  min_recommendations: 20
  eval_k_multiplier: 4

# Параметры оценки
evaluation:
  k: 5  # Основной k для метрик (Precision@k, NDCG@k, Hit Rate@k)
  recall_k: 20  # k для Recall@k
  ndcg_k: 10  # k для NDCG@k
  popular_k: 100  # Количество популярных товаров для fallback
  degradation_threshold: 0.1  # Порог деградации модели (10%)

